
// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// AUTH
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';


// GENERAL REQUESTS
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// AUTH RELATED
export const INITIAL_SIGNUP_SUCCESS = 'INITIAL_SIGNUP_SUCCESS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';

// POST RELATED
export const GET_POST = 'GET_POST';
export const GET_POSTS = 'GET_POSTS';
export const POST_LOADING = 'POST_LOADING';
export const ADD_POST = 'ADD_POST';
export const DELETE_POST = 'DELETE_POST';
export const LIKE_POST = 'LIKE_POST';
export const GET_POST_ERRORS = 'GET_POST_ERRORS';

    // POST REPLY RELATED
    export const ADD_REPLY = 'ADD_REPLY';
    export const GET_REPLIES = 'GET_REPLIES';
    export const GET_REPLY = 'GET_REPLIES';
    export const GET_REPLY_ERRORS = 'GET_REPLY_ERRORS'

// PROFILE RELATED
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_LOADING = 'PROFILE_LOADING';
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
export const GET_PROFILES = 'GET_PROFILES';
// PROFILE COMMENTS RELATED
export const ADD_PROFILE_COMMENT = 'ADD_PROFILE_COMMENT';
export const GET_PROFILE_COMMENT = 'GET_PROFILE_COMMENT';
export const GET_PROFILE_COMMENTS = 'GET_PROFILE_COMMENTS';
export const LIKE_PROFILE_COMMENT = 'LIKE_PROFILE_COMMENT';
export const DELETE_PROFILE_COMMENT = 'DELETE_PROFILE_COMMENT';

// PRODUCTS RELATED (product DB)
export const PRODUCTS_LOADING = 'PRODUCTS_LOADING';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT = 'GET_PRODUCT';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';

    // USER CART RELATED
    export const CART_LOADING = 'CART_LOADING';
    export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
    export const DELETE_PRODUCT_FROM_CART = 'DELETE_PRODUCT_FROM_CART';
    export const CLEAR_USER_CART = 'CLEAR_USER_CART';

export const GET_USER_CART = 'GET_USER_CART'; // items in user cart
export const REMOVE_ITEM_FROM_USER_CART = 'REMOVE_ITEM_FROM_USER_CART' // remove item from user cart
export const GET_CURRENT_CART_TOTAL = 'GET_CURRENT_CART_TOTAL'; //current cart total


// ORDERS RELATED user cart
export const ORDERS_LOADING = 'ORDERS_LOADING';
export const GET_ORDERS = 'GET_ORDERS';
export const GET_ORDER = 'GET_ORDER';
export const GET_ALL_ORDERS = 'GET_ALL_ORDERS'; // gets all orders
export const SUBMIT_ORDER = 'SUBMIT_ORDER';

// RESUME RELATED
export const GET_RESUME = 'GET_RESUME';
export const GET_RESUMES = 'GET_RESUMES';
export const POST_RESUME = 'POST_RESUME';
export const RESUME_LOADING = 'RESUME_LOADING';

// ARTICLES RELATED
export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ARTICLES = 'GET_ARTICLES';
export const ARTICLES_LOADING = 'ARTICLES_LOADING';

// TODO RELATED ACTIONS
export const GET_TODOS = 'GET_TODOS';
export const ADD_TODO = 'ADD_TODO';
export const REMOVE_TODO = 'REMOVE_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const CHANGE_TODO_STATUS = 'CHANGE_TODO_STATUS';
export const GET_TODO = 'GET_TODO'; // when you hit the edit button, populate the todo form.
export const GET_SORTED_TODOS = 'GET_SORTED_TODOS';

// PAGE HISTORY
export const GET_LASTPAGE_HISTORY = 'GET_LASTPAGE_HISTORY';




